flyntwp/flynt-starter-theme

- Features/GoogleAnalytics/GoogleAnalytics.php
- Features/GoogleAnalytics/script.twig
...and other minor improvements
> Features/GoogleAnalytics: use twig template for script rendering

- Features/AdminNotices/AdminNoticeManager.php
- Features/AdminNotices/README.md
Readme file fix: messages needs to be an array. Refactored array indentations inside the class.
> refactor(Features/AdminNotices):  readme file fix and indentation refactoring

- Features/AdminComponentPreview/functions.php
Usinng Asset Utils to load components preview images
> fix(Features/AdminComponentPreview/functions): Fixed assets path and url

- Components/DocumentDefault/BaseStyles/Mixins/_fontFace.styl
- remove old chrome windows hack, add font-style parameter
- use more practical level of browser support
> Components/DocumentDefault: revamp fontface helper

- Components/BlockVideoOembed/howto.md
Added 1 explanation line: remove the `required: 1` option inside the `posterImage` field.
> refactor(Components/BlockVideoOembed/howto): Added one explanation line

- templates/archive.php
`archive-unfiltered.json` does not exist
> fix(archive): Switched to archive.json instead of archive-unfiltered.json

- Components/DocumentDefault/BaseStyles/Mixins/_fontFace.styl
- Components/SliderMedia/style.styl
to fix console error with slick font loading
resolves #191
> fix(Components/DocumentDefault): add woff2 option to fontFace helper

- lib/Utils/Log.php
Log postponed to wp_footer action, but can also be bypassed
> fix(Log class): Log postponed to wp_footer action

- Components/ListPosts/howto.md
Using Timber `get_preview` function instead of using custom functions from TimberHelper Util class.
> refactor(Components/ListPosts/howto.md): Modified the Manual Post Teaser selection example

- Features/HideProtectedPosts/README.md
- Features/HideProtectedPosts/functions.php
- lib/Init.php
Remove from query password protected posts if not in a singular page or in admin
> feat(HideProtectedPosts): Remove from query password protected posts

- lib/Utils/ArrayHelpers.php
DocBlocks added. objectToArray function removed.
> feat(lib/Utils/ArrayHelpers.php): DocBlocks added.

- Components/BlockImage/index.twig
- Components/BlockMediaText/Partials/Image/index.twig
- Components/BlockMediaText/Partials/OembedVideo/index.twig
- Components/BlockVideoOembed/Partials/OembedVideo/index.twig
- Components/SliderMedia/Partials/Image/index.twig
- Components/SliderMedia/Partials/OembedVideo/index.twig
fixes image sizes attribute and incorrect aspect ratios in several components
> fix(Components): use correct image sizes and ratios

- gulpfile.js/config.js
- gulpfile.js/tasks/replaceVersion.js
- package.json
- yarn.lock
- in PHP DocBlocks %%NEXT_VERSION%% is replaced
- in WordPress theme's style.css
closes #220
> build(npm): replace version in files on release

- lib/Utils/Feature.php
> feat(lib/Utils/Feature.php): Added Docblocks.

- templates/page.php
- templates/single.php
> refactor(templates): remove unnecessary page and single templates

- Features/TinyMce/config.json
now grouped and use correct button classes by default
> fix(Features/TinyMce): use correct styleformats in config

- .travis.yml
was limited due to #192, but that appears to have been fixed now
> ci(Travis): use phpcs ~3.1

- .gitignore
> fix(.gitignore): Add Yarn Error Log

- Features/TimberLoader/functions.php
Also includes a small refactor.
> feat(Features/TimberLoader): add template file name filter

- Features/Acf/admin.js
> fix(Features/Acf/admin.js): fix expand/close all buttons

- lib/Init.php
These don't need to be added by default and should be added where necessary.
> refactor(lib/Init): remove post formats

- Components/BlockCookieNotice/index.twig
- Components/GridContentLists/index.twig
- Components/GridPosts/index.twig
- Components/GridPostsSlider/index.twig
- Components/GridTeaserTiles/index.twig
- Components/HeroCta/index.twig
- Components/ListComponents/index.twig
- Components/ListPostCards/index.twig
- Components/ListSearchResults/Partials/Header/index.twig
- Components/ListSearchResults/Partials/Pagination/index.twig
- Components/ListSearchResults/functions.php
- Features/ComponentLogServer/functions.php
- inc/assets.php
- lib/Utils/Options.php
- lib/Utils/TwigExtensionFlynt.php
- templates/search.php
- templates/twig/search.twig
some minor refactorings and adjustments. will merge. just for reference.
> Componentlibrary adjustments
